version: '3.9'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@airflow_postgres_container:5432/airflow
    - AIRFLOW__CORE__FERNET_KEY=h-X5VAyfboV8odeksnnqXmkFIL8DcclOOVDzBAFQ_2g=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
  volumes:
    - ./AIRFLOW/dags:/opt/airflow/dags
    - ./AIRFLOW/airflow-data/logs:/opt/airflow/logs
    - ./AIRFLOW//airflow-data/plugins:/opt/airflow/plugins
    - ./AIRFLOW//airflow-data/airflow.cfg:/opt/airlfow/airflow.cfg
  depends_on:
    - airflow_postgres
  networks:
    - dwh_postgres

services:
  #flask_api
  flask_api:
    hostname: flask_api_container
    container_name: flask_api_container
    build: ./API
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://dwh_postgres:dwh_postgres@dwh_postgres_container:5433/dwh_postgres_db
    depends_on:
      - postgres
    networks:
      - dwh_postgres

  #DWH postgresSQL
  postgres:
    hostname: dwh_postgres_container
    container_name: dwh_postgres_container
    build: ./DWH
    volumes:
      #path to file share
      - ./DWH/file_share/dwh_postgresql_data/:/var/lib/postgresql/data
      - ./DWH/file_share/init:/docker-entrypoint-initdb.d
      - ./DWH/file_share/dumps/:/var/lib/postgresql/dumps
    #set the DB name, user and password
    environment:
      POSTGRES_USER: 'dwh_postgres'
      POSTGRES_PASSWORD: 'dwh_postgres'
    ports:
        - '5433:5433'
    networks:
      - dwh_postgres

  #pgadmin
  pgadmin:
    hostname: pgadmin_container
    container_name: pgadmin_container
    build: ./PGADMIN
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@default.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpswrd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    #path to file share
    volumes:
      - ./PGADMIN/file_share/pgadmin_data/:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - dwh_postgres

  #airflow
  airflow_postgres:
    host_name: airflow_postgres_container
    container_name: airflow_postgres_container
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init &&
        airflow users create
          --role Admin
          --username airflow
          --password airflow
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow )
    restart: on-failure

  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    restart: always

  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    restart: always

networks:
  dwh_postgres:
    driver: bridge